<?php

namespace AppBundle\Repository;

/**
 * ProfessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProfession($value = '')
    {
        $qb = $this->createQueryBuilder('p')
            ->where('p.title LIKE :title')
            ->setParameter('title', "%{$value}%")
            ;

        $result = $qb
            ->getQuery()
            ->getResult()
        ;

        return $result;
    }
}
